Api: ✏️ 월별 지출내역 조회시 발생하는 N+1 문제 개선
CollaBu/pennyway-was pull request #110
Opened 2024-06-06 11:03 UTC by asn6878

## 작업 이유
- `Spending` 객체와 연관관계를 맺고있는 `SpendingCustomCategory` 객체가 존재.
- 기존의 `QueryDSL` 확장 레포지토리를 통한 월별 지출내역 조회시, N+1 문제 발생
- `SpendingSearchService` 에서 확장 레포지토리에 전달하는 `QueryHandler`의 내용을 `fetchJoin`을 사용토록 수정

<br/>

## 작업 사항
> 로직 개선에 사용된 라인은 5줄 미만입니다. 싹 다 테스트코드에요!

![image](https://github.com/CollaBu/pennyway-was/assets/79460319/bee111f3-26e2-490f-9209-eeb58121749b)

테스트코드를 작성하면서 `SpendingCustomCategoryFixture`가 필요해지고, 커스텀 카테고리를 가지는 지출내역의 Insert가 필요해지면서 변경사항이 길어졌습니다. **박살난 가독성을 위해 최대한 요약해 설명해보겠습니다.**

> 작성한 `SpenidngSearchServiceTest`의 흐름은 아래와 같습니다.
> - 커스텀 카테고리를 랜덤하게 만들어서 bulkInsert
> - 그 커스텀 카테고리를 가지는 `Spending` 들을랜덤하게 만들어서 bulkInsert
> - 이때 이번달 지출내역을 조회
> - 조회된 `Spending` 들의 `spendingCustomCategory`에 접근
> - 쿼리 횟수 검증

이때 Hibernate가 발생시키는 쿼리는 2회 이며, 이를 만족하지 않을시 테스트는 실패합니다.
1. `Spending` 과 `SpendingCustomCategory` 객체들의 user가 될 `User`객체를 create할때 1회
2. `readSpendings`시 1회
<br/>

## 리뷰어가 중점적으로 확인해야 하는 부분
- 테스트코드에 잘못된 부분이 있는지?
- `fetchJoin()` 사용이 적절한지?

<br/>

## 발견한 이슈
X

2024-06-06 11:56 UTC, psychology50 commented
일단 리뷰 전에... 여기선 커스텀 카테고리 N+1 테스트를 하고 싶은 거라서 랜덤 값을 삽입하는 것보다는 그냥 3~4개 정도의 커스텀 카테고리로 등록된 지출 내역 데이터를 등록하시는 게 더 나았을 거예요.

2024-06-06 13:01 UTC, psychology50 requested changes
기존 테스트를 재활용하신 거니 수정하실 필요는 없지만, N+1 테스트를 위해 통합 테스트를 사용하는 건 비효율적입니다.  
DAO 계층 테스트 케이스를 작성해서, 응답값을 given 절로 처리하면 DB 연결조차 생략 가능해요.

2024-06-06 13:43 UTC, psychology50 commented on pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/fixture/SpendingCustomCategoryFixture.java
> 단순히 상수값으로 하나의 SpendingCustomCategory를 활용하면 추가적인 쿼리연산이 1회 발생할 것이고

지금도 이미 발생하고 있지 않나요?

2024-06-06 13:45 UTC, asn6878 commented on pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/fixture/SpendingCustomCategoryFixture.java
fetch 하지 않을 때를 기점으로 말씀하시는 건가요?

2024-06-06 13:47 UTC, asn6878 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/SpendingSearchService.java
이 부분은 제가 듣고도 깜빡한 것 같네요 :(
말씀주신 방법대로 적용토록 하겠습니다!

2024-06-06 13:48 UTC, psychology50 commented on pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/fixture/SpendingCustomCategoryFixture.java
아아, 제가 잘못 이해했어요. 상수 하나를 사용하면 추가 쿼리가 1번 밖에 발생하지 않기 때문이라는 거군요.  
그럼 상수 여러개 정의하고 벌크 연산하는 건 어떤가요. 랜덤값으로 정하면 검증할 때 너무 힘들어져서 그래요.  

한 3개 정도 상수로 만들고 벌크연산하면 원하시는 목적도 이루고, 테스트 편의성도 갖출 수 있을 거 같아요.

2024-06-14 01:44 UTC, psychology50 reviewed
웬만하면 그냥 승인하려고 했는데, 정렬 부분 하나 확인 부탁드려요~

2024-06-14 01:44 UTC, psychology50 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingService.java
P5: 얾..제가 의도했던 건 SearchService에서 Predicate를 사용하지 않고, SpendingService 내에서 사용하는 게 좋을 거 같다는 의미긴 했어요. 그러면 `findList`를 사용해도 무방하거든요.  
여튼 문제가 reject 시킬 만한 건은 아닌 거 같아서 패스하겠습니다.

2024-06-14 01:44 UTC, psychology50 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingCustomRepositoryImpl.java
> +                .orderBy(orderSpecifiers.toArray(new OrderSpecifier[0]))
P1: 이건 분명히 잘못 된 거 같은데, 쿼리문에 oreder가 정상적으로 삽입되고 있는지 확인 부탁드려요!

![image](https://github.com/CollaBu/pennyway-was/assets/96044622/9db83e2e-0f70-4653-afd3-2a1a777bf67b)

기존에는 `spendAt`이라는 필드로 정렬을 해줬었는데, 지금은 그게 안 되고 있을 거 같습니다.

2024-06-23 19:23 UTC, asn6878 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingCustomRepositoryImpl.java
> +                .orderBy(orderSpecifiers.toArray(new OrderSpecifier[0]))
저번에 대면으로 이야기 나눈 내용인걸로 기억합니다! 위에 `orderSpecifiers`를 선언하는 부분을 지나치신듯 합니다.

일단 명확한 확인을 위해 테스트에 정렬되어있음을 검증하는 구문을 추가 후 성공함을 확인하였습니다 :)
![image](https://github.com/CollaBu/pennyway-was/assets/79460319/aacd38f4-ceb6-4270-b768-c16fbd90ebe9)
![image](https://github.com/CollaBu/pennyway-was/assets/79460319/5af09659-3d48-41c8-a6b0-c0dad6041428)

2024-06-23 21:54 UTC, psychology50 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingCustomRepositoryImpl.java
> +                .orderBy(orderSpecifiers.toArray(new OrderSpecifier[0]))
넵, 확인했습니다~

2024-06-23 21:55 UTC, psychology50 approved these changes

2024-06-23 22:01 UTC, merged