Api: ✨ 소비내역 복수 삭제 API
CollaBu/pennyway-was pull request #119
Opened 2024-06-30 20:24 UTC by asn6878

## 작업 이유
복수개의 소비내역을 삭제하는 API 필요.

<br/>

## 작업 사항

### API Spec
- url : `DELETE /v2/spendings`
- pre-condition : 사용자는 로그인 한 상태이고, 삭제하고자 하는 지출 내역들의 작성자여야 한다.

결과 응답
```json
{
  "code" : "2000",
  "data" : { }
}
```

<br/>

## 리뷰어가 중점적으로 확인해야 하는 부분
- `deleteAllById` 사용이 적절한지?
- 더 검증할 테스트 케이스가 있는지?
- 요청 URL이 적절한지?

<br/>

## 발견한 이슈
진작에 `deleteAllById`를 사용하면 됐는데, 멍청하게 QueryDSL을 활용해서 직접 다 구현하다가 뒤늦게 깨닫는 멍청비용을 소모하였습니다.
![image](https://github.com/CollaBu/pennyway-was/assets/79460319/0f601962-fca7-4090-8b6f-6b820e1b1bed)

2024-07-01 03:18 UTC, psychology50 requested changes
테스트가 실패한 상태긴 하지만, 현재 작업하신 부분까지 리뷰 남깁니다~

2024-07-01 03:18 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authorization/SpendingManager.java
> +    public boolean hasPermissions(Long userId, List<Long> spendingIds) {
P3: 자원 검사를 위해 hasPermissions를 사용하신 것 같습니다! 다만, 한 가지 우려스러운 점은 현재 방법은 N개의 spending pk 자원 검사를 위해, N번의 쿼리를 호출하게 된다는 점입니다. (지금 삭제하는 방법까지 합치면 총 2N + (영속화 횟수 N)이 되겠네요.)   
그래서 아래 방법처럼 한 번의 쿼리로 해결하는 방법은 어떻게 생각하시나요?

![image](https://github.com/CollaBu/pennyway-was/assets/96044622/d44b7ebc-d964-4381-b6d4-c293692d6b94)

`IN` 절을 이용하여, 유효한 user_id를 가지면서 pk가 올바른 전체 row의 수를 카운팅하고 결과를 반환하면 `spedingIds의 size`와 동일해야 한다는 조건입니다.  
더 나은 방법이 있을 거 같긴 한데, 거기까진 좀 더 고민해봐야 할 듯..ㅎ

2024-07-01 03:18 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/SpendingIdsDto.java
> +        @NotNull(message = "지출 내역 ID 목록은 필수입니다.")
P4: 자료 구조에는 `@NotEmpty`를 써주면, {"spendingIds":[]} 같은 요청을 방지해줄 수 있는 것으로 알고 있습니다. 다만 null 조건도 같이 막아주는 지는 기억이 안 나네요 허허.

2024-07-01 03:18 UTC, psychology50 commented on pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/SpendingControllerIntegrationTest.java
P5: 이건 그냥 요새 드는 매우매우 주관적인 생각일 뿐이라 수정하실 필요까진 없어요. 저희가 테스트 시간이 짧게는 2m 30s, 길게는 3m이 넘게 걸릴 때가 있어서 생각해보니 과하게 통합 테스트에 의존하기 때문이 아닐까 싶습니다.  
그래서 전 보다 단위 테스트에 집중하려고 하고 있어요. 단위 테스트와 통합 테스트 각각 어디까지 테스트하는 것이 좋을 지 논의해보는 시간을 가져보는 것도 좋을 거 같습니다~

2024-07-01 18:44 UTC, asn6878 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/SpendingIdsDto.java
> +        @NotNull(message = "지출 내역 ID 목록은 필수입니다.")
https://velog.io/@suzhanlee/NotNull-NotEmpty-NotBlank-%EC%A0%95%EB%A6%AC

`@NotNull` : null만 막음
`@NotEmpty` : null, 빈 객체(빈 리스트, 빈 문자열 등...)들만 막음
`@NotBlank` : null, 빈 객체 뿐만 아니라 공백까지 막음

덕분에 찾아보고 확실하게 알게됐네요! 여기는 `@NotEmpty` 쓰겠슴다ㅎ

2024-07-01 19:26 UTC, asn6878 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authorization/SpendingManager.java
> +    public boolean hasPermissions(Long userId, List<Long> spendingIds) {
저도 `Count수 != 리스트.size()`  조건으로 검사하는 것 이상으로 좋은 방법이 생각나지 않아
```java
@Transactional(readOnly = true)
Integer countByUserIdAndIdIn(Long userId, List<Long> spendingIds);
```
해당 쿼리와 동일한 동작을 수행하는 JPA 메소드를 작성해 권한 검증 로직 수정하였습니다!

2024-07-02 11:37 UTC, asn6878 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingService.java
> +        spendingRepository.deleteAllById(spendingIds);
```java
    @Modifying(clearAutomatically = true)
    @Transactional
    @Query("UPDATE Spending s SET s.deletedAt = NOW() where s.id IN :spendingIds")
    void deleteAllById(List<Long> spendingIds);
```

좋은 생각인것 같습니다. 이 고민을 처음에 안했던것은 아니었긴 한데, 사실 지출내역 삭제 한번에 해봤자 얼마나 하겠어...? 라는 생각으로 그냥 했던 것 같습니다 😅 
그렇지만 부작용이나 구현에 크게 어려움이 있는 것이 아니기 때문에 위처럼 jpql 사용토록 해 적용 하였습니다.
> `@Modifying(clearAutomatically = true)`에 대해서도 다시 공부했습니다. 감사합니다~

2024-07-02 15:17 UTC, psychology50 reviewed
하나 확인이 필요한 게 있어서 커멘트 남깁니다!  
다른 하나는 의견이 궁금해서 남겨요

2024-07-02 15:17 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authorization/SpendingManager.java
> +        if (spendingService.countByUserIdAndIdIn(userId, spendingIds) != spendingIds.size()) {
P3: Integer 타입을 비교하실 때 `.equals()`를 쓰셔야 할 거 같은데, 확인 부탁드려도 될까요??  
[참고 블로그](https://dev-typo.tistory.com/21)를 읽어보시면 제 질문을 이해하실 수 있을 거예요.  
아니면 `count~` 메서드 반환 값을 `int`로 해버리는 것도 나쁘지 않을지도?? `.size()`의 반환값도 int였던 거 같은디

2024-07-02 15:17 UTC, psychology50 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingRepository.java
> +    void deleteAllById(List<Long> spendingIds);
P5: 이건 전에 제가 고민하던 건데..bulk 연산으로 처리하는 메서드는 메서드 명으로 알려주는 게 어떤가요? 아무래도 캐시 불일치 문제 때문에 주의가 필요한데, 나중에 다른 곳에서 사용할 일이 생길 때쯤이면 잊어먹어서 문제가 생길 수도 있을 거 같아요.  

![image](https://github.com/CollaBu/pennyway-was/assets/96044622/0d4f2bb0-5499-4eec-9206-c09631d8f700)

물론 저도 전에 안 해서 ㅎㅎ 의견이 궁금해서 커멘트 남겨봅니당.

2024-07-02 19:04 UTC, asn6878 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingRepository.java
> +    void deleteAllById(List<Long> spendingIds);
`deleteAllById` 라는 메서드명을 벌크연산 처리하는 행위 자체가 말씀주신 캐시 불일치 문제때문에 조심스러워 고민을 했었습니다.
하지만 저는 **`Spending` 이라고 하는 객체를 여러개 삭제하는 동작**이 필요한 유즈케이스가 단 하나뿐이라고 판단해 그냥 진행했었어요! 바꾸는게 좋을까요?

2024-07-03 04:54 UTC, psychology50 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingRepository.java
> +    void deleteAllById(List<Long> spendingIds);
엇, 도메인 서비스는 유즈 케이스 관점에서 보면 위험하다고 봐요. 그보다는 시스템(모듈) 관점에서 보는 게 맞다고 생각합니다. ㅎㅎ  
성윤님 말씀대로 현재 유즈 케이스만 따진다 쳐도, "사용자 삭제"와 "지출 카테고리 삭제" 등에서도 쓰일 수 있긴 해요.  

저도 근데 이 부분은 정답을 정하고 이야기하려던 건 아니라서 ㅋㅋㅋ 이야기를 해보고 싶어서 커멘트 남겼어용.  
전 도메인 서비스에서 벌크 연산을 사용하는 경우 명시적으로 표현해서 나쁠 게 없다고 생각합니다!

2024-07-03 13:58 UTC, asn6878 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingRepository.java
> +    void deleteAllById(List<Long> spendingIds);
> 성윤님 말씀대로 현재 유즈 케이스만 따진다 쳐도, "사용자 삭제"와 "지출 카테고리 삭제" 등에서도 쓰일 수 있긴 해요.

음, 제가 생각했던것 보다 우려되는 예외상황들이 좀 있네요.
메서드 명 변경하겠습니다ㅎ 확인부탁드려요!

2024-07-03 15:26 UTC, psychology50 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingRepository.java
> +    void deleteAllById(List<Long> spendingIds);
Repository 레벨의 메서드에 `InQuery`를 넣으셨네요.  
혹시 Domain Service 레벨의 메서드에선 어떻게 할까요? 메서드 명이 아니라면 주석으로 명시해주는 게 좋지 않을까요?

2024-07-03 17:51 UTC, asn6878 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingRepository.java
> +    void deleteAllById(List<Long> spendingIds);
생각해보니 추후 마주할 메서드이름이 Domain Service 메서드인데 그생각을 안했네요ㅋㅋㅋ
동일하게 Domain 레벨 메서드에도 InQuery 접미사 붙이겠습니다ㅎ

2024-07-03 18:06 UTC, asn6878 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authorization/SpendingManager.java
> +        if (spendingService.countByUserIdAndIdIn(userId, spendingIds) != spendingIds.size()) {
`spendingService.countByUserIdAndIdIn(userId, spendingIds)` 메서드의 반환타입을 `Integer`로 보신 것 같은데
희한하게도  이게 service 레벨에서는 반환타입이 `long`이고, repository 레벨에서는 `Integer`로 해놨었네요ㅋㅋㅋ... 그것도 통일하겠습니다.

2024-07-04 05:20 UTC, psychology50 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingRepository.java
> +    void deleteAllById(List<Long> spendingIds);
저도 전에 제가 만들어놓은 메서드 나중에 수정해두겠습니다~

2024-07-04 05:24 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authorization/SpendingManager.java
> +        if (spendingService.countByUserIdAndIdIn(userId, spendingIds) != spendingIds.size()) {
아, 메서드 반환 값이 long이네요. 사실 반환 값이 int 타입 최대값을 넘어설 일이 존재하지 않을 거 같아 문제가 되진 않겠지만, long 타입과 int 타입을 암묵적 형변환으로 비교하면 좀 꺼름칙하긴 한데...혹시 명시적 형변환을 하는 건 어떤가요?

2024-07-04 08:57 UTC, asn6878 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authorization/SpendingManager.java
> +        if (spendingService.countByUserIdAndIdIn(userId, spendingIds) != spendingIds.size()) {
명시적 형변환으로 변경 완료했습니다~~

2024-07-04 09:18 UTC, psychology50 commented
merge하고 불러주시면 바로 승인하겠습니다~

2024-07-04 14:47 UTC, psychology50 approved these changes

2024-07-04 16:57 UTC, merged