Feat/pw 115 question
CollaBu/pennyway-was pull request #36
Opened 2024-04-07 08:03 UTC by asn6878

## 작업 이유
- 문의 메일 작성 API 구현

<br/>

## 작업 사항
### 1️⃣ 문의 메일 발송 API 작성
- Figma를 참고해 사용자의 이용 흐름에따라 문의 메일을 관리자의 메일로 발송하는 API를 구현하였습니다.

![postman](https://github.com/CollaBu/pennyway-was/assets/79460319/1bf4e852-0518-45ba-942e-291de993bd9f)
![mail1](https://github.com/CollaBu/pennyway-was/assets/79460319/a45c0c38-a283-49aa-b846-092252a667a6)
![mail2](https://github.com/CollaBu/pennyway-was/assets/79460319/ce8f2c23-1380-450e-9ae2-eb00238b7d91)

<br/>

## 리뷰어가 중점적으로 확인해야 하는 부분
- 메일 발송시 사용되는 Private한 정보들을 `application.yml`에 작성하였습니다. 환경설정 파일을 다루는데에 아직 미숙하여 지금 작성한대로 사용해도 괜찮을지 봐주시면 감사하겠습니다. (환경변수 값들은 Notion Private 페이지에 업로드 해두겠습니다!)
- `QuestionUsecase` 와 `QuestionMapper`를 일단 마구잡이로 써보았는데... 피드백 주시면 감사하겠습니다.
- 전에 언급해주신 Event Handling은 전혀 사용되지 않은 상태입니다. 이부분 역시 지속적으로 피드백 반영하여 구현하겠습니다.

<br/>

## 발견한 이슈
없음

2024-04-07 15:04 UTC, psychology50 requested changes
저의 애정과 사랑을 듬뿍 담은 PR을 올립니다!  
우선 현재 올린 커멘트부터 해결하면서 차근차근 개선해봐요. ㅎㅎ

2024-04-07 15:04 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/question/usecase/QuestionUseCase.java
UseCase를 어떻게 할 지는 일단 다른 커멘트 해결되면 다시 이야기해봐요!

2024-04-07 15:04 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/question/mapper/QuestionMapper.java
P2: 전에 제가 `Mapper`와 `Helper`를 구분하는 나름의 기준을 말씀드렸는데, 
- `createMessage`는 과연 Mapper에 들어오는 메서드가 맞을까요? 어떠한 DB 관련 요청을 가공하고 있나요? 
- `createSubject`와 `createContent`는 Mapper 클래스의 책임이 맞을까요?
- `createQuestion`가 DB에 저장되는 작업이 있다면 `@Transactional`이 필요하진 않았을까요?

2024-04-07 15:08 UTC, asn6878 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/SecurityConfig.java
> +                                .anyRequest().permitAll()
앗, 이부분은 일단 실행시켜보는 과정에서 임시로 변경한 부분이었는데, 깜빡하고 처리하지 않은채로 커밋에 반영되어 버렸네요.
위험한 실수였던것 같은데 꼼꼼히 확인해주셔서 감사합니다.😢 
적절한 방법으로 수정해두겠습니다!

2024-04-09 16:17 UTC, asn6878 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/question/controller/QuestionController.java
> +    @PostMapping("/send")
단순히 `문의를 보냄` 이라고 생각을 해서 달아둔것 같은데,
`/questions` 리소스에 직접 POST를 사용하는 것이 RESTful 디자인의 원칙을 더 잘 따르는 방법인것 같아요!

2024-04-10 07:40 UTC, asn6878 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/question/domain/Question.java
> +    @ColumnDefault("NULL")
테이블 생성시 사용했던 DDL입니다.
```sql
CREATE TABLE question (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255),
    category VARCHAR(255),
    content TEXT,
    created_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP DEFAULT NULL
);
```
이상태로 아래와 같은 요청을 보내면,
```json
{
  "email": "asn6878@gmail.com",
  "content": "test 이메일입니다.",
  "category": "UTILIZATION"
}
```
정상적으로 DB에 저장 및 실행되는것을 확인했습니다.
ddl 에서 미리 명시해준 constraints 와 관계없이, `@ColumnDefault` 만으로 null을 명시해주지 않은경우에도 알아서 dao까지 null로 잘 넘어가는 것 같아요!

2024-04-10 08:46 UTC, psychology50 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/question/domain/Question.java
> +    @ColumnDefault("NULL")
음, 혹시 ColumnDefault 어노테이션을 제거하면 어떻게 되나요?

2024-04-10 08:48 UTC, asn6878 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/question/domain/Question.java
> +    @ColumnDefault("NULL")
근데 아까 디코에서 말씀드린거 고민하다가, 백오피스 환경을 고려해본다 하더라도 `문의` 라는 주제 자체가 삭제 혹은 변경될일이 없다 판단하여 `createdAt` 필드 빼고는 다 제거해버린 상태긴 합니다.

다시 만들어서 한번 해보고 결과 공유해드릴게요.

2024-04-10 09:17 UTC, asn6878 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/question/domain/Question.java
> +    @ColumnDefault("NULL")
`@ColumnDefault("NULL")` 없이도 위와 동일한 상황에서 정상 동작하네요.

제가 이 어노테이션의 이해도가 부족한 것 같아 좀 찾아봤는데, 앞서 말씀해주신 `@DynamicInsert` 가 수반되어야 정상 동작한다는 말씀이 맞습니다!

다만 그 상황은 `@ColumnDefault("NULL")` 이아닌 `@ColumnDefault("foo")` 처럼 null이 아닌 default값을 명시해줄 필요가 있을때에만 의미가 있을것 같아요.

+ 재서님이 디코에서 언급해주신것 처럼 `@ColumnDefault`도 hibernate의 `auto-ddl`이 DDL을 생성해줄때만 사용되어 동작하네요!!

결론적으로 본 경우는 제가 애초에 nullable한 필드에 `@ColumnDefault("NULL")`을 의미없이 명시해 사실상 해당 어노테이션은 아무것도 안하고있었던 삽질케이스 인것 같다는 결론을 내렸습니다. 🤮 
좋은 공부하게 해주셔서 감사합니다!

2024-04-10 09:20 UTC, psychology50 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/question/domain/Question.java
> +    @ColumnDefault("NULL")
아, 아뇨. 이 경우엔 DB 자체에 default 값으로 `NULL`을 명시해줬기 때문일 수도 있습니다.  
전에 제가 했을 때는 분명히 실패했었는데, 그 때는 DDL에 `Defulat Null`을 명시해줄 정도로 꼼꼼하진 않았었거든요.  

이게 잘못하면 테스트 환경에서 실패할 수도 있어서, 죄송하지만 DB에서 Default 값 Null을 제거하고 `@ColumnDefault`가 없는 조건에서도 성공하는지 확인 부탁드려도 될까요?

2024-04-10 09:53 UTC, asn6878 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/question/domain/Question.java
> +    @ColumnDefault("NULL")
말씀해 주신대로 DB에 `deleted_at` 필드의 Default 값을 따로 명시하지 않고,
기존의 DB에 `question` 테이블을 DDL을 사용해 Default 값을 명시하지 않아 보았습니다.
- 실행한 쿼리
```sql
ALTER TABLE question
DROP COLUMN deleted_at;

// drop후 새로 생성
ALTER TABLE question
ADD COLUMN deleted_at TIMESTAMP;
```

결론부터 말씀드리자면 **DB에서도 해당 필드가 NULL에 대한 명시가 따로 없으면 Nullable로 생성해 기존에 `Default Null`을 DDL에서 명시해줬을 때와 같은 속성으로 생성 되는 것을 확인했습니다! (MySQL은 일단 이렇게 동작하는것 같습니다.)**

그래서 **그럼 ddl-auto로 생성될때는 어떻게 생길까?** 가 궁금해져서 테이블을 아예 날리고, `domain` 모듈의 `hibernate` 옵션을 `ddl-auto: update` 로 주고 기존의 테이블을 `drop` 하여 실행해보았습니다. 

- `Question.java`의 `deletedAt` 필드에는 여전히 `@ColumnDefault` 어노테이션이 없는 환경입니다.
```java
@Entity
@Getter
@Table(name = "Question")
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@EntityListeners(AuditingEntityListener.class)
public class Question {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String email;
    private QuestionCategory category;
    private String content;
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    private LocalDateTime deletedAt;
...
```

- hibernate 가 실행한 테이블 상태( NOT NULL을 따로 명시하지 않아 Default값으로 NULL이 자동으로 들어간 모습)
![image](https://github.com/CollaBu/pennyway-was/assets/79460319/e2147902-ad7d-4c95-80ab-5251b9526c58)

- 실행 결과
![image](https://github.com/CollaBu/pennyway-was/assets/79460319/af5dc3fd-f0e6-42fe-b6b9-56552850af33)
![image](https://github.com/CollaBu/pennyway-was/assets/79460319/939fff94-f0c1-4b86-afaf-65a928f814f2)

정리 해보자면, 일단 DDL과 Entity그 어느곳에서도 해당 속성은 Default가 NULL이다! 라고 명시해주지 않아도 알아서 NULL로 들어가는 것을 확인했습니다!

2024-04-10 10:24 UTC, psychology50 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/question/domain/Question.java
> +    @ColumnDefault("NULL")
생성할 때 `Null`을 명시 안 해줘도 default를 알아서 Null로 잡는 건 또 처음 알았네요 ㅋㅋㅋㅋㅋㅋ  

![image](https://github.com/CollaBu/pennyway-was/assets/96044622/7cbd1788-43d0-4003-8458-03682f782e56)

우선 제가 말씀드렸던 건, 저기서 더블 클릭하면 Null을 지울 수 있는데 그러면 DB에서도 default 값이 없어서 실패할 수도 있을 거 같아요.  
하지만 성윤님 말씀대로라면 `ddl-auto: create`를 하더라도 Null을 허용한 이상 default도 알아서 잡힐테니 문제가 없을 것 같네요.  

상세한 테스트와 정보 공유 감사드립니다~

2024-04-10 10:38 UTC, asn6878 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/question/mapper/QuestionMapper.java
- `createMessage`는 과연 `Mapper`에 들어오는 메서드가 맞을까요? 어떠한 DB 관련 요청을 가공하고 있나요?
Mapper의 역할을 "단순히 비즈니스 로직을 수행하는데 필요한 특정객체를 매핑해 반환해주는 역할"로 생각했던것 같습니다. 이 메소드는 지금 보니 굳이 따지면 유틸성이 강하다고 생각해 `Helper`로 분리해주는게 더 좋을것 같기도 한데, 재서님은 어떻게 생각하시는지 궁금해요!

- `createSubject`와 `createContent`는 Mapper 클래스의 책임이 맞을까요?
이또한 같은 맥락이라고 생각합니다. 위와 동일한 의견이에요!

- `createQuestion`가 DB에 저장되는 작업이 있다면 `@Transactional`이 필요하진 않았을까요?
단순히 직접 Repository의 메소드를 호출하는 메소드들만 달아주면 된다고 생각했는데, DB에 액세스 하는 동작과 관련되어있으면 상위 메소드들도 어노테이션을 달아줘야 하는걸 몰랐던것 같습니다. 반영 하겠습니다 :)

2024-04-10 11:10 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/question/mapper/QuestionMapper.java
> * `createMessage`는 과연 `Mapper`에 들어오는 메서드가 맞을까요? 어떠한 DB 관련 요청을 가공하고 있나요?
>   Mapper의 역할을 "단순히 비즈니스 로직을 수행하는데 필요한 특정객체를 매핑해 반환해주는 역할"로 생각했던것 같습니다. 이 메소드는 지금 보니 굳이 따지면 유틸성이 강하다고 생각해 `Helper`로 분리해주는게 더 좋을것 같기도 한데, 재서님은 어떻게 생각하시는지 궁금해요!

일반적으로 Helper는 Util의 성격을 가지고, 그렇기 때문에 특정 Domain에 국한되지 않습니다. (그야 그게 Util이니까)  
비록 저 또한 `jwtAuthHelper`에서 `User` 도메인을 인자로 받긴 했지만, 분명히 잘못되었다고 PR에 명시해두기도 했구요.  
하지만 그 경우엔 `jwtAuthHelper`는 언제나 인증 기능에서만 사용되며, DB와 연결하는 작업이 아니기 때문에 그냥 규칙을 다소 무시하고 진행한 거였습니다.

여기까진 Helper에 대한 이야기였고, 개선 방향은 다른 관점으로 봐야 합니다.  
**"`JavaMailSender`가 `external-api`**의 관심사가 맞느냐?"가 우선적으로 되어야 해요. 

Mail을 보내기 위해선 외부 Actor와 통신이 발생합니다.  
하지만 `external-api` 모듈은 `presentation` 계층에 속하는 로직에만 관심이 있기 때문에, 이 부분은 애초에 `infra` 모듈에 존재하는 게 맞다고 생각해요.  
 
하지만 mail을 보내는 주체가 어디(google, naver 등)일 지는 알 수 없으니, OCP 원칙에 의해 일단 MailSend를 위한 인터페이스를 정의하고, 구현체를 만들어야 할 겁니다.  
그리고 해당 구현체를 Bean으로 등록하고, 실제 메일을 전송하는 `send()`의 책임은 해당 구현체에게 넘기는 게 올바른 관심사 분리라 생각합니다.

내용이 많이 어려울 거예요...보다 자세한 설명이 필요하면 아키텍처를 그려서 설명해드릴게요.

> * `createSubject`와 `createContent`는 Mapper 클래스의 책임이 맞을까요?
>   이또한 같은 맥락이라고 생각합니다. 위와 동일한 의견이에요!

`createQuestion`은 `Question` 엔티티를 생성하고 반환하는 로직만을 포함합니다.  
`Mapper` 클래스란 보통 여러(혹은 단일) DB(혹은 테이블)와 상호작용하여, DTO를 가공하기 위해 사용해요.  

그런데 이 경우엔 그저 `Question` Entity를 **생성 → 저장**이 끝입니다.  
이 정도를 처리하기 위해 Mapper 클래스까지 생성하는 것은 오히려 낭비라고 봐요.

> * `createQuestion`가 DB에 저장되는 작업이 있다면 `@Transactional`이 필요하진 않았을까요?
>   단순히 직접 Repository의 메소드를 호출하는 메소드들만 달아주면 된다고 생각했는데, DB에 액세스 하는 동작과 관련되어있으면 상위 메소드들도 어노테이션을 달아줘야 하는걸 몰랐던것 같습니다. 반영 하겠습니다 :)

`@Transactional`은 default로 실행하면 하위로 전파됩니다.  
만약 하나의 UseCase가 여러 DomainService 로직을 호출한다고 하면, 그 중 하나라도 실패했을 때 모두 실패하게 처리하려면 **UseCase에 `@Transactional`을 명시**해주면 됩니다.

2024-04-10 11:29 UTC, psychology50 requested changes
대화 몇 개가 해결되어 추가해놨습니다~

2024-04-10 11:29 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/question/api/QuestionApi.java
> +    @Schema(name = "QuestionReqGeneral", title = "문의 요청")
P1: `@Schema`는 API 설명을 위한 springDoc 어노테이션이 아닙니다. req body와 res body의 정보를 위해 존재하는 어노테이션이예요!

2024-04-10 11:29 UTC, psychology50 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/question/domain/Question.java
> +    private QuestionCategory category;
P1: 이렇게 하면 `QuestionCategory` 상수값이 문자열로 저장될 거예요. 이는 저장 공간 낭비이기 때문에 저희는 상수 값을 각각의 정수로 대응시켜 변환하는 방식을 채택하기로 했었습니다!  
그걸 쉽게 하기 위해 [User Domain 설정 PR](https://github.com/CollaBu/pennyway-was/pull/15)에서 명시했었고,  [사용법은 여기를](https://github.com/SoftwareEngineeringYU/SoftwareEngineering-BE/pull/18) 참고하시면 됩니다.

2024-04-10 11:29 UTC, psychology50 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/question/domain/Question.java
> +    @CreatedDate
수정 반영된 거 확인했습니다~

2024-04-10 11:29 UTC, psychology50 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/question/service/QuestionService.java
> +    @Transactional
반영된 거 확인했습니다!

2024-04-10 11:29 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/question/controller/QuestionController.java
> +        return ResponseEntity.ok(SuccessResponse.from(question));
P2: 저희가 정했던 응답 포맷 컨벤션은 다음과 같습니다.  
```json
// 성공
{
   "code" : "2000",
   "data" : { // data의 값은 언제나 Object
       "domain": { // "domain(단수명사)" 값 Object, "domains(복수명사)" 값 배열
          ...
       }
   }
}
```

하지만 성윤님의 응답은 아래와 같죠.

![image](https://github.com/CollaBu/pennyway-was/assets/96044622/9e59c341-ea6e-4f55-b1d9-9fcb5e9f2c11)

응답 포맷의 일관성이 깨진다고 프로그래밍 에러가 발생하는 경우는 드물겠지만, Client 입장에서 난처해지게 됩니다. API에 대한 신뢰성이 깨질 수 있어요.  

그러나 고려해볼 점이 한 가지 더 있습니다.  
Client가 과연 요청에 대해 저장된 Question 도메인 정보를 궁금해할까요?  
그저 `성공 여부`만 알려주면 될 겁니다.  

즉 `SuccessResponse.noContent()`를 응답으로 보내버리고 끝내버려도 됩니다.

2024-04-10 11:31 UTC, psychology50 commented on pennyway-app-external-api/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-mail'
버전 명시된 거 확인했습니다~

2024-04-10 11:41 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/question/api/QuestionApi.java
> +    @Parameter(name = "email", description = "문의자 이메일")
`@Parameter`를 없애고 `@Schema`를 넣어버리셨군요...😇 일단 이 Conversion은 resolve 처리 하겠습니다.

2024-04-10 11:41 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/question/api/QuestionApi.java
> +            @ExampleObject(name = "이용 관련", value = "UTILIZATION"), @ExampleObject(name = "오류 신고", value = "BUG_REPORT"), @ExampleObject(name = "서비스 제안", value = "SUGGESTION"), @ExampleObject(name = "
다 날리셨군요 ㅋㅋㅋ 확인했습니다~

2024-04-10 11:42 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/question/controller/QuestionController.java
> +@RequestMapping("/v1/question")
url 변경 확인했습니다~

2024-04-10 11:42 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/question/dto/QuestionReq.java
> +    public record General(
내부 클래스 제거 확인했습니다!

2024-04-13 17:52 UTC, asn6878 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/question/controller/QuestionController.java
> +        return ResponseEntity.ok(SuccessResponse.from(question));
처음에 `noContent()` 로 할까 고민을 하긴했었는데... 재서님 말씀들어 보니 확실히 반환할 이유가 없네요. 반영했습니다!

2024-04-15 10:44 UTC, psychology50 reviewed
지속적으로 변경되고 있는 거 확인하고 있어요 ㅎㅎ

2024-04-15 10:44 UTC, psychology50 commented on pennyway-app-external-api/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-mail:3.2.3'
얘가 이제 infra 쪽으로 옮겨지면 되겠죠? ㅎㅎ

2024-04-15 10:44 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/question/mapper/QuestionMapper.java
회의에서 말씀드린 것처럼 이 Mapper는 완전히 없앨 수 있게 되었습니다!  
JavaMailSender는 infra 모듈로 옮기고, UseCase에서 Question Domain Service에 저장한 후에 eventPublisher에 event를 등록만 해주면,  
infra 모듈에서 `@TransactionalEventListener`를 통해서 mail을 전송해줄 수 있어요.

2024-04-15 10:44 UTC, psychology50 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/question/domain/QuestionCategory.java
앗, 혹시 Conveter 적용이 잘 되던가요?  
혹시나 안 되면 `@JsonCreator`를 사용했어야 했을 수도..

2024-04-15 10:56 UTC, asn6878 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/question/domain/QuestionCategory.java
![image](https://github.com/CollaBu/pennyway-was/assets/79460319/e58602bc-69cb-459b-ac61-5a8540a40bca)
테스트 케이스를 작성을 안하니 이런부분이 검증이 까다롭네요ㅠ

DB에 tinyint 형태로 잘 변환되어 저장되는것 확인 했습니다! (`UITLIZATION` => `"1"`)

2024-04-16 03:35 UTC, psychology50 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/question/domain/QuestionCategory.java
뭐야 되네 ㅋㅋㅋㅋㅋ. 안 될 줄 알았는데 다행이네요.

2024-04-18 02:20 UTC, psychology50 reviewed
와, 진짜 많이 바뀌었네요. 조금만 더 하면 될 것 같아요!!  
현재 `external-api`의 엉뚱한 테스트 케이스에서 실패가 뜨는데, 로컬 환경에서 `./gradlew --info --parallel test` 실행해보시고 로그 확인해볼 필요가 있을 듯 합니다.

2024-04-18 02:20 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/question/api/QuestionApi.java
P2: BE 개발자는 API 문서를 친절히 정리할 의무가 있다고 생각합니다. 특히 best practice에 해당하는 성공 응답만큼이나, 클라이언트가 반드시 핸들링해야 하는 예외 응답도 신경쓰는 것이 마땅하구요.  
입력 포맷 에러와 같은 프로그래밍 에러를 자세하게 작성할 의무는 없다고 생각합니다. 하지만 메일 전송에 실패한 경우엔 어떤 응답이 반환되나요? 이는 분명히 서버 측 에러이며, 클라이언트가 이를 핸들링할 수 있도록 문서에 명시해주어야 합니다.

2024-04-18 02:20 UTC, psychology50 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/question/domain/QuestionCategory.java
> +    public String getCode(){
P5: `@Getter` 어노테이션이 있는데 `getCode()`를 따로 오버라이딩하신 이유가 있을까요?

2024-04-18 02:20 UTC, psychology50 commented on pennyway-infra/src/main/java/kr/co/pennyway/infra/common/event/MailEventHandling.java
> +        log.debug("handleMailEvent: {}", event);
P4: log 레벨이 debug가 아니어도 될 거 같아요! 오히려 info 레벨로 남겨두면 좀 더 유용할 수도 있을 것 같습니다.

2024-04-18 02:20 UTC, psychology50 commented on pennyway-infra/src/main/java/kr/co/pennyway/infra/config/MailConfig.java
P5: 이건 혹시나 모르실 수도 있을 것 같아서 적어둘게요.  
`@Value`를 필드나, 생성자, setter에 사용하면 값이 주입되는 시점에 차이가 발생합니다.  
- [간략하지만 이해가 잘 되는 설명](https://way-be-developer.tistory.com/292)
- [조금 더 자세한 설명](https://velog.io/@tidavid1/Spring%EC%97%90%EC%84%9C-Value%EC%9D%98-%EA%B0%92%EC%9D%80-%EC%96%B8%EC%A0%9C-%EB%B0%98%EC%98%81%EB%90%A0%EA%B9%8C)

2024-04-18 02:20 UTC, psychology50 commented on pennyway-infra/src/main/resources/application-infra.yml
> +  question-address: ${ADMIN_ADDRESS}
P3: 말씀하신 것처럼 `ADMIN_ADDRESS`는 오해의 여지가 있을 것 같아요.  
차라리 `GOOGLE_ADMIN_ADDRESS`나 `GOOGLE_ADMIN_EMAIL`이 더 나을 것 같습니다!

2024-04-18 06:12 UTC, asn6878 commented on pennyway-infra/src/main/resources/application-infra.yml
> +  question-address: ${ADMIN_ADDRESS}
관리자의 이메일 주소는 플랫폼(구글)에 국한되지 않는다고 생각해 ADMIN~~이라는 네이밍을 했어요. (저희 팀 공식계정은 현재 구글계정이긴 합니다만) 그래서 `ADMIN_ADDRESS` 앞에 플랫폼 명을 붙이는게 어색할것 같은데, 재서님 생각은 어떠세요?

2024-04-18 06:23 UTC, psychology50 commented on pennyway-infra/src/main/resources/application-infra.yml
> +  question-address: ${ADMIN_ADDRESS}
이미 mail.host를 gmail로 못박아둔 상태에서 크게 의미가 있을 듯 한데, 성윤님 의견이 그러하다면 mail host 또한 환경 변수로 등록하는 것이 맞지 않았나 생각합니다.

그러면 범용성을 갖는 환경 변수명이 좀 더 의미가 있을 것 같구요.

2024-04-18 06:42 UTC, asn6878 commented on pennyway-infra/src/main/resources/application-infra.yml
> +  question-address: ${ADMIN_ADDRESS}
이게 약간 뒤죽박죽이라 오해의 소지가 있는거 같아서, 한번만 더 이해관계 확인함에 양해부탁드립니다 😥

- `mail.host` 에 사용되는 값은 `JavaMailSender`가 메일을 발송하는데에 사용할 smtp 서버를 의미합니다. 즉 발송자(team.collabu@gmail.com) 입니다.

- `ADMIN_ADDRESS` 는 서버가 발행한 메일을 발송받을(서버에서 발생시킨 메일 내용을 누구한테보내지?) 수신자의 메일주소를 결정짓는 변수입니다.

서버에서 요청받은 문의 내용을 메일로 수신받을 계정이 foobar@naver.com 이라고 가정했을 때 전달흐름 동작 예시입니다.

<hr/>

`ADMIN_ADDRESS` = foobar@naver.com

```json
URL => v1/questions 
Request Body  =>
{
  "email": "asn6878@gmail.com",
  "content": "문의사항 있는데요",
  "category": "UTILIZATION"
}
```
### from `team.collabu@gmail.com`
### to `foobar@naver.com`
문의사항있는데요~~~

<hr/>

이러한 환경에서 어짜피 메일을 발송하는 주체(`mail.host`)는 `GOOGLE`로 고정되어 있지만, 메일을 발송받을 주소는 naver나 다른 곳이 될수있다고 생각하여 플랫폼에 국한되지 않는다고 생각했습니다!

2024-04-18 07:16 UTC, psychology50 commented on pennyway-infra/src/main/resources/application-infra.yml
> +  question-address: ${ADMIN_ADDRESS}
아하, 저는 수신 쪽에 맞춰서 `mail.host`를 설정한다고 생각했었는데 잘못 이해하고 있었네요.  
그럼 `ADMIN_ADDRESS`도 괜찮을 것 같다고 생각해요!

2024-04-18 07:17 UTC, psychology50 commented on pennyway-infra/src/main/resources/application-infra.yml
> +  question-address: ${ADMIN_ADDRESS}
그보다 `ADMIN_ADDRESS` 환경 변수에도 임시 변수값 지정해주셔야 할 거 같습니다!

2024-04-20 09:06 UTC, asn6878 commented
코멘트 달아주신 부분들 일괄 반영처리 완료하였습니다! 시간 나실때 검토 해주시면 감사하겠습니다 :)

2024-04-20 10:10 UTC, psychology50 approved these changes
와~ 피드백 반영하시느라 정말 수고 많으셨어요.  
코드 모두 확인했습니다!

2024-04-20 13:08 UTC, merged