일반 회원 아이디 찾기 API 구현
CollaBu/pennyway-was pull request #48
Opened 2024-04-15 15:14 UTC by jinlee1703

## 작업 이유

- `/v1/find/username` API를 통한 일반 회원 아이디 찾기 API 구현

<br/>

## 작업 사항

- [x] 기존에 있던 `AuthCheckController`에서 `AuthCheckApi` 생성 후 분리
- [x] `/v1/find/username` API 구현
- [ ] `AuthCheckUseCase`의 `findUsername` 메서드 구현
  - [ ] 등록되지 않은 전화번호(계정)일 경우 - 404 예외 처리
  - [ ] OAuth 계정일 경우 - 401 예외 처리 (오늘 대면에서 이야기한 내용과 시퀀스 다이어그램이 다름)
- [ ] 테스트 코드 작성
  - [ ] `AuthCheckUseCase`의 `findUsername` 메서드 테스트 코드 작성
  - [ ] `/v1/find/username` API 테스트 코드 작성
 
<br/>

## 리뷰어가 중점적으로 확인해야 하는 부분

- 현재 예외처리가 전혀 되어있지 않은 코드입니다.
- 크게 구현한 내용은 없지만 방향성이 맞는지 확인 차 draft pr 제출합니다.
- `?phone=xxx-xxxx-xxxx` 형태(하이픈 포함)로 전화번호를 받아오고 있는데 이 부분 문제가 없는 지 궁금합니다.

<br/>

## 발견한 이슈

- 없음

2024-04-15 15:40 UTC, psychology50 reviewed
하나 빼곤 전부 p4, p5네요.  
우선 올려주신 거 빠르게 확인했습니다~

2024-04-15 15:40 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthCheckController.java
> +    public ResponseEntity<?> findUsername(@RequestParam @Validated String phone) {
P4: 예전에 든 의문이었는데, phone은 사용자 개인정보에 해당하는데 query param으로 보내는 게 맞는지 고민이었어요.  
엄연히 보안이 중시되는 데이터라 생각해서 모두 request body로 옮긴 적이 있는데, 진우님 의견이 궁금합니다.

2024-04-15 15:40 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthCheckController.java
> +    @PreAuthorize("permitAll()")
P3: username을 검색하는 건, 미인증 유저를 위한 api기 때문에 `isAnonymous()`여야 할 것 같아요!  
`checkUsername`(지금보니 메서드명 너무 구림)이 permitAll인 이유는 나중에 로그인한 사용자가 username 변경할 때가 있어서 이렇게 해둔 거였어요.

2024-04-15 15:40 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthCheckController.java
> +                SuccessResponse.from("username",
P4: 응답 포맷을 이렇게 하는 건 어떤가요? ㅋㅋ  

```json
{
   "code": "2000",
   "data": {
       "user": {
            "username": "..."
       }
   }
}
```

2024-04-15 15:40 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/AuthCheckUseCase.java
> +                .orElse(null);
P5: 아, 예외 처리 안 되어있다고 한 게 이거군요 ㅎㅎ

2024-04-15 15:59 UTC, jinlee1703 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthCheckController.java
> +    public ResponseEntity<?> findUsername(@RequestParam @Validated String phone) {
사실 저도 의문이 드는 부분이었습니다! `아이디 찾기 API`는 `조회`에 가깝다 보니 GET 메서드로 구현을 했었는데, 기본적으로 GET 메서드를 사용할 때는 request body를 사용하지 않는 것을 원칙으로 하는 것으로 알고 있어서 확신이 안드네요...

2024-04-16 02:42 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthCheckController.java
> +    public ResponseEntity<?> findUsername(@RequestParam @Validated String phone) {
아, 브루트포스로 대입해보는 건 예상 못 했던 부분이네요.  
듣고보니 변경하는 게 더 나을 것 같다는 생각이 듭니다 ㅎㅎ

2024-04-17 04:04 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthCheckController.java
> +    public ResponseEntity<?> findUsername(@RequestParam @Validated String phone) {
네이버 인증 요청을 확인해봤더니 GET 요청을 보내더라구요.  
다만, 말씀하신대로 브루트 포스 공격으로 데이터를 조회할 수도 있다는 점을 감안하면, 추후 server to server를 위한 자체 보안 검증 단계를 추가할 필요성이 있을 듯 합니다.

2024-04-17 12:19 UTC, psychology50 requested changes
디스코드에서 말씀드린대로, 현재 인증 코드를 확인하는 작업이 수행되고 있지 않는 부분에 대한 수정이 필요합니다!

![image](https://github.com/CollaBu/pennyway-was/assets/96044622/40cf6667-4336-474d-9c48-1c8b5ead88c7)

작업하시느라 수고 많으십니다 😇

2024-04-17 12:19 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/SecurityConfig.java
> +    private static final String[] READ_ONLY_PUBLIC_ENDPOINTS = {"/favicon.ico", "/v1/duplicate/**", "/v1/find/**"};
P1: `READ_ONLY_PUBLIC_ENDPOINTS`는 security 단에서 public으로 열어버리는 엔드포인트에 해당하는데, `ANONYMOUS_ENDPOINTS`로 옮기는 게 나을 거 같아요!  
물론 지금도 MethodSecurity로 막고 있기 때문에 문제가 생기진 않겠지만요.

2024-04-17 12:19 UTC, psychology50 commented on pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthCheckControllerTest.java
> +@TestClassOrder(ClassOrderer.OrderAnnotation.class)
P5: 아 ㅋㅋㅋ 이거 필요 없는 어노테이션이예요.  
테스트의 순서를 보장하고 싶을 때 사용하는데, 저는 중첩된 클래스로 여러 테스트 케이스 클러스터를 실행했기 때문에 `@TestClassOrder`를 사용했고,  
만약 진우님도 똑같이 하고 싶다면, 현재 메서드 레벨의 테스트밖에 없기 때문에 `@TestMethodOrder(MethodOrderer.원하는_옵션.class)`를 선택하고 메서드마다 `@Order`로 순서를 지정해주면 됩니다.  

하지만 현재 Order를 사용하지 않으신 걸로 보아 그럴 의도는 아니셨던 것 같아 말씀드려요!

2024-04-17 12:19 UTC, psychology50 commented on pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthCheckControllerTest.java
> +		given(authFindMapper.findUsername(inputPhone)).willReturn(new AuthFindDto.FindUsernameRes(expectedUsername));
P2: `@ExternalApiIntegrationTest` 어노테이션은 실제 실행 환경처럼 모든 빈을 주입하기 때문에, `@MockBean`이 아니라 `@Autowired` 어노테이션으로 실제 빈을 주입받으시면 돼요!  
그러면 `given()`을 사용할 이유도 없어집니다.  

동작에 문제는 없겠지만, 불필요한 객체 생성이 테스트에 포함되므로 P2로 격상 ㅎ  
물론 아래 테스트도 마찬가지입니다.

---

아, 그런데 지금 하고 계신 건 사실상 통합 테스트가 아니라 Controller 계층 Unit Test인 것 같습니다.  
그러면 통합 테스트 어노테이션을 사용하신 건 과했던 것 같아요.  

제가 전에 Controller 계층 Unit Test를 했던 `AuthControllerValidationTest`를 보시면 알 수 있습니다.  
단, 해당 방법으로 Unit Test를 할 때 주의점이 있습니다. 예전 PR에 작성했으므로 찾아보시면 돼요!!

2024-04-18 15:38 UTC, jinlee1703 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/AuthCheckApi.java
> +    ResponseEntity<?> findUsername(@RequestParam @Validated String phone);
`@Validated` 어노테이션의 경우에는 '닉네임 중복 검사' API를 참고하여 개발하다보니 용도도 모르고 붙였네요 ㅠㅠ `@NotNull` 어노테이션은 추가하겠습니다!
현재(`@NotNull` 추가 후) 각 케이스에 따른 응답 결과는 다음과 같습니다.

1. query string에 `phone`이 없을 경우
  <img width="1521" alt="image" src="https://github.com/CollaBu/pennyway-was/assets/68031450/f60abeb5-3d76-430e-aa75-09a211ed8311">

2. query string에 `phone`이 null일 경우, `phone`의 양식이 잘 못 되었을 경우(ex: `01012345678`)
  <img width="1531" alt="image" src="https://github.com/CollaBu/pennyway-was/assets/68031450/a37f446c-1ccf-4e50-ad2c-d04206e436fa">

2024-04-18 16:07 UTC, jinlee1703 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/mapper/AuthFindMapper.java
> +			log.error("User not found by phone: {}", phone);
오 재밌는 주제인거 같습니다! 간단하게 [stackoverflow](https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels) 이 주제에 대해 다룬 게시글이 있는데, 가장 많은 동의를 받은 의견을 첨부하겠습니다.

Trace - 코드를 "추적"하고 구체적으로 함수의 한 부분을 찾으려고 할 때만 가능합니다.
Debug - 개발자(IT, 시스템 관리자 등) 이상의 사람들에게 진단적으로 도움이 되는 정보입니다.
Info - 일반적으로 기록할 유용한 정보(서비스 시작/중지, 구성 가정 등)입니다. 정보 항상 사용할 수 있기를 원하지만 일반적으로 일반적인 상황에서는 신경 쓰지 않습니다. 이것이 내 기본 구성 수준입니다..
Warn - 잠재적으로 응용 프로그램에 이상한 문제를 일으킬 수 있지만 자동으로 복구되는 모든 항목입니다. (예: 기본 서버에서 백업 서버로 전환, 작업 재시도, 보조 데이터 누락 등)
Error - 작업에 치명적 이지만 서비스나 애플리케이션에는 치명적이지 않은 오류입니다(필수 파일을 열 수 없음, 데이터 누락 등). 이러한 오류는 사용자(관리자 또는 직접 사용자) 개입을 강제합니다. 이는 일반적으로 잘못된 연결 문자열, 누락된 서비스 등을 위해 (내 앱에서) 예약되어 있습니다.
Fatal - 데이터 손실(또는 추가 데이터 손실)을 방지하기 위해 서비스나 애플리케이션을 강제 종료하는 오류입니다. 나는 데이터 손상이나 손실이 확실하게 발생하는 가장 심각한 오류 및 상황에 대해서만 이를 예약합니다.

위 게시글을 읽고 `info`, `warn`, `error` 이 세가지 로그 레벨에 대한 제 생각은 아래와 같습니다.

`info` - 일반적으로 기록하기 위한 로그 레벨
`warn` - 현재 유효하지 않은 휴대폰과 같은 예외에 해당하는 로그 레벨
`error` - `warn`보다 치명적인 오류를 위한 로그 레벨 (지금 당장 예를 들만한 것이 생각이 안 나네요..)

2024-04-18 16:09 UTC, jinlee1703 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/mapper/AuthFindMapper.java
> +			return new AuthFindException(AuthFindErrorCode.NOT_FOUND_USER);
관리 측면에 대해서는 생각하지 못했네요! 말씀해주신대로 1번(`UserErrorCode` 재사용)이 가장 좋은 방법인 것 같아요.

현재 response가 `{ 'user': { 'username': '...' } }`으로 응답을 주기 때문에 전혀 이질감이 들지 않는 것 같습니다.

2024-04-18 17:02 UTC, jinlee1703 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/AuthCheckUseCase.java
> +    public String findUsername(String phone) {
`UseCase`를 사용하려 했으나, 바로 `Mapper`(현재는 Service)를 호출하는 실수를 했네요 ㅠㅠ
사용하도록 수정했습니다!

2024-04-18 17:06 UTC, jinlee1703 commented
> 디스코드에서 말씀드린대로, 현재 인증 코드를 확인하는 작업이 수행되고 있지 않는 부분에 대한 수정이 필요합니다!
> 
> ![image](https://private-user-images.githubusercontent.com/96044622/323213397-40cf6667-4336-474d-9c48-1c8b5ead88c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NTkzNzksIm5iZiI6MTcxMzQ1OTA3OSwicGF0aCI6Ii85NjA0NDYyMi8zMjMyMTMzOTctNDBjZjY2NjctNDMzNi00NzRkLTljNDgtMWM4YjVlYWQ4OGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDE2NTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MjI1OWU1NjQ1OTRjYjUxNDY4NzNiYTBiMzRmNzQ2MDI3YjY1NzdmYzU2YjM3MWQ1NTU1YzFiZjkwMjhhODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wxyWvDIZifQEujWz8KVp1Z_t9XBfRkBSQa1ERVPmpno)
> 
> 작업하시느라 수고 많으십니다 😇

말씀하신 대로라면 `아이디 찾기 API`에서도 redis를 조회하여 인증 코드 전송 API를 통해 만들어진 코드가 존재하는 휴대폰 번호가 있는지 검사헤야 한다는 말씀이실까요?

2024-04-19 14:14 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/AuthCheckApi.java
> +    ResponseEntity<?> findUsername(@RequestParam @Validated String phone);
`@NotNull`은 단순히 null 여부만 판단하기 때문에, `@NotBlank`가 보다 나을 것 같아요.  
그렇게 하면 null 뿐만 아니라, 빈 문자열로 넘어온 값도 거부할 수 있습니다!

2024-04-19 14:17 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/mapper/AuthFindMapper.java
> +			log.error("User not found by phone: {}", phone);
현재 예외처리하고 있는 부분은 모두 `error` 레벨은 아닌 것 같고 `warn`이라고 하기에도 애매한 것 같아요.  
사용자를 찾지 못 한 것도, 사용자의 password가 null인 것도 이번 비지니스 로직 내에선 그저 또 다른 하나의 결과일 뿐이니까요.  

이런 경우엔 로그 수준을 `info`로 맞춰도 괜찮지 않을까요?

2024-04-19 14:22 UTC, psychology50 commented
> 말씀하신 대로라면 `아이디 찾기 API`에서도 redis를 조회하여 인증 코드 전송 API를 통해 만들어진 코드가 존재하는 휴대폰 번호가 있는지 검사헤야 한다는 말씀이실까요?

넵, 맞습니다.  
인증 코드 검증을 안 하면, 전화번호로 닉네임을 검색하려는 사용자가 올바른 절차를 통해 API를 호출한 건지 알 수가 없어서 필요해요.    

1. `phone`으로 아이디 검색 (인증 목적의 `code`를 함께 전송)
2. `phone`으로 `code` 유효성 검사.
3. `phone`으로 `user` 검색
4. 종료 후 `username:phone`에 해당하는 redis 값 제거 

생각해보니 이 부분 저 혼자 만들거라 생각해서 어떻게 사용하는 지 설명은 안 적어둔 거 같은데..

2024-04-19 14:31 UTC, psychology50 reviewed
피드백 반영 굿...👍  
인증 코드 사용자한테 받아서 검사하는 로직이랑 모두 끝나고 캐시에서 제거하는 것만 추가해주시면 될 것 같아요!

2024-04-19 14:31 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/mapper/AuthFindService.java
P4: 지금 이대로 해도 상관없고, 아래는 그냥 의견입니다.  
도메인 서비스에서 `Optional<User>`로 값을 받아오고, 해당 User의 *isEmtpy*() 여부와 *getPassword*()로 oauth 유저를 검사하는 부분을 메서드로 분리하면 보다 명시적으로 표현 가능할 것 같아요.  
그리고 그 메서드...어차피 비밀번호 수정할 때 쓰게 되실 거구 ㅎㅎ. 나중에 패스워드 찾기 기능 만드실 때 고려해보셔도 좋을 것 같습니다.

2024-04-19 14:31 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/mapper/AuthFindService.java
> +@Mapper
P1: `@Mapper`가 아니라 이제 `@Service`로 바꿔주시면 됩니다!

2024-04-20 02:25 UTC, jinlee1703 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/mapper/AuthFindService.java
추후 반영하겠습니다!

2024-04-20 04:22 UTC, psychology50 commented
redis에서 인증번호를 확인을 하기 위해 고려 사항과 하셔야 할 작업 정리해둘게요.  

### 1️⃣ VerificationType Query Pamameter 필요 여부 확인
SmsController의 `@RequestParam(value = "type") VerificationType type, @RequestParam(name = "provider", required = false) Provider provider`를 보시면 이해가 되실 거예요.  
이건 Oauth가 아니니 `Provider`는 필요 없습니다.   

`VerficiationType`을 받아야 할 텐데, 만약 아이디 찾기와 비밀번호 찾기 API와 함수를 분리한다면 필요 없습니다.  

<br/>

### 2️⃣ 인증 번호 검사/삭제

<div align="center">
   <img src="https://github.com/CollaBu/pennyway-was/assets/96044622/bec42021-1a92-48c7-a8fd-60a369b44fd3" width="700px"/>
</div>

(리팩토링한다고 이름이 바뀌어서 헷갈리실 텐데, `PhoneVerficationService` ⇾ `PhoneVerificationMapper`, `PhoneCodeService` ⇾ `PhoneVerificationService` (제 거 ⇾ 진우님 거)입니다.)  

아이디 찾기 API에서는 인증코드 연장이 필요 없으므로 *isValid()* 검사 후, 캐시에 저장된 인증코드를 *delete*() 해주면 됩니다.  

하지만 나중에 만드실 비밀번호 찾기 API는 인증 코드 유효성 검사 후, 사용자에게 다시 비밀번호를 입력받아야 하기 때문에 인증코드 ttl 연장이 추가되어야 해요.  

isValid 메서드는 다음과 같이 사용하시면 됩니다.  
```java
phoneVerificationService.isValidCode(request, PhoneCodeKeyType.FIND_USERNAME);
```

2024-04-24 03:38 UTC, psychology50 approved these changes
시험 이슈로 너무 늦게 확인했네요 ㅜ  
변경 사항 모두 확인했습니다. 수고하셨어요!

2024-04-24 05:56 UTC, merged