✨ 비밀번호 찾기 API
CollaBu/pennyway-was pull request #71
Opened 2024-05-01 13:46 UTC by asn6878

## 작업 이유
 `/v1/find/password` API를 통한 일반 회원 아이디 찾기 API 구현

<br/>

## 작업 사항
- [ ] API 작성
- [ ] 테스트코드 작성

### 🕹️ 동작 시나리오
![image](https://github.com/CollaBu/pennyway-was/assets/79460319/b4e54491-8ce5-4318-80da-fc1f9e4b845d)
`code`, `phone`, `newPassword`를 `RequestBody`로 전달받아, Redis에 `CodeType`이 `FIND_PASSWORD`고, 정보가 일치하는 유효한 데이터가 존재 할 시 해당 데이터를 삭제하고 비밀번호를 바꿉니다.
추가적으로, 비정상적인 요청(Oauth 유저의 비밀번호를 찾는 요청)을 방지하기 위한 부분도 처리하였습니다.

캐싱된 인증번호 정보를 검증하는부분, 비밀번호를 업데이트하는 부분이 대부분 이미 작성되어있어서 사실 가져다 쓴게 전부입니다. 😅 

일단 BestPractice를 제외하고는 **전혀 테스트해본바가 없어**, 테스트 케이스를 작성하며 놓친 디테일한 부분들 보완 예정입니다. 이부분 참고해주시면 감사하겠습니다!

<br/>

## 리뷰어가 중점적으로 확인해야 하는 부분
`PhoneCodeService`에서 기존 아이디찾기 로직과 중복되는 부분들을 private 메소드들 (`readUserOrThrow`, `checkUserPassword`)로 분리하였습니다.
이에 기존 아이디찾기 API에 영향이 없음은 확인 했습니다만, 문제될 부분이 있는지 확인해주시면 감사하겠습니다 😄 

<br/>

## 발견한 이슈
없음.

2024-05-01 16:24 UTC, psychology50 requested changes
허허, 갑자기 변경 사항을 덤으로 드리게 되어 죄송해요.  

디스코드로 다시 말씀드린 것처럼 비밀번호 찾기 시나리오에선 API가 총 2개가 필요해요.  
다른 하나도 구현해서 올려주시면 리뷰하겠습니다~!

2024-05-01 16:24 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthCheckController.java
> +        String passwordReq = request.newPassword();
P4: 굳이 변수화 하지 않고 `request.newPassword()`를 바로 인자로 넣어도 괜찮을 거 같아요!

2024-05-01 16:24 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/AuthCheckUseCase.java
> +    @Transactional
P5: 그냥 재미삼아..여긴 Transaction이 필요 없습니다 ㅎㅎ ㅋㅋ 영속화 될 것도 없고, authFindService 가 끝이라서~

2024-05-01 16:24 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/service/AuthFindService.java
> +        if (password == null) {
P2: User Entity에는 제가 정의해둔 `isGeneralSignedUpUser()` 메서드가 있을 겁니다. 보다 직관적으로 바꿀 수 있을 거예요.

2024-05-01 16:24 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/service/AuthFindService.java
> +    // 유저 존재 여부 검증
P4: 이 주석과 아래의 "// Oauth 회원 여부 검증" 주석 모두 불필요하다고 봐요.  
왜냐면 함수가 매우 짧고 직관적이어서 주석 없이도 충분히 이해가 가거든요.

2024-05-01 16:24 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/service/AuthFindService.java
> +    private String checkUserPassword(User user) {
P5: 이 메서드가 하고 싶은 일은 분명 "비밀번호 검사"가 맞긴 하겠지만, 그보다는 "일반 회원가입 여부 검사"라는 의미를 갖는 메서드명이 좀 더 적절할 것 같아요! 어떻게 생각하시나요?

2024-05-01 16:24 UTC, psychology50 commented on pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/mapper/AuthFindServiceTest.java
> +        String phone = "010-2629-4624";
아니 ㅋㅋㅋㅋㅋㅋㅋ 테스트 코드에 제 진짜 번호 넣으면 어떡해요. ㅜㅜ 어쩐지 스팸 문자 날아오더라.  
Swagger에 제 휴대폰 번호 넣은 이유는 다들 아무 생각없이 예시 번호에다 보내버려서 어쩔 수 없이 해놓은 거였어요

2024-05-01 16:24 UTC, psychology50 commented on pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/mapper/AuthFindServiceTest.java
> +        System.out.println(exception.getExplainError());
P3: 저도 실수한 부분이긴 한데, 테스트 코드 쓰실 때도 `log.debug()` 쓰심 됩니다~

2024-05-01 16:24 UTC, psychology50 commented on pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/mapper/AuthFindServiceTest.java
> +        User user = User.builder()
P3: User를 직접 생성하는 것도 좋지만, `User user = UserFixture.OAUTH_USER.toUser()`를 써보시면 재밌는 일이 벌어질 거예요 ㅎㅎ

2024-05-01 16:24 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/service/AuthFindService.java
> +        if (passwordEncoderHelper.isSamePassword(user.getPassword(), newPassword)) {
요거 없애주세용...ㅎㅎ 그냥 수정시켜줘야 할 거 같슴다.

2024-05-02 02:54 UTC, asn6878 commented on pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/mapper/AuthFindServiceTest.java
> +        String phone = "010-2629-4624";
엇, 사실 `AuthFindServiceTest.java`는 제가 작성한 파일이 아니긴해요 😅 
깃에 이렇게 기록된건 제가 아마 저 테스트파일명을 변경(기존의 Mapper가 Service로 바뀜)하면서 새로 작성된것 처럼 된것 같아요!

해당 파일에 코멘트 적어주신부분은 확인후에 기존 코드에 반영해보겠습니다! :)

2024-05-02 07:51 UTC, asn6878 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/AuthCheckApi.java
> +                    @ExampleObject(name = "기존 비밀번호 불일치", value = """
제가 모니터링 했던 비밀번호 찾기 -> 비밀번호 수정 흐름을 가지는 몇개 서비스들이 기존 비밀번호와 동일할 시 실패해서, 제가 아무생각없이 저희 서비스 정책을 바꿔버렸네요...

말씀해주신대로, UseCase에 맞게 로직 변경처리 해두겠습니다!

2024-05-06 09:46 UTC, merged