✨ 지출 내역 수정 API
CollaBu/pennyway-was pull request #93
Opened 2024-05-16 10:58 UTC by asn6878

## 작업 이유
사용자는 지출 내역을 수정할 수 있다.

<br/>

## 작업 사항

### API Spec
- url : `PUT /v2/{지출내역 ID}`
- pre-condition : 사용자는 로그인 한 상태이고, 조회하고자 하는 지출 내역의 작성자 여야 한다.

결과
![image](https://github.com/CollaBu/pennyway-was/assets/79460319/aa283d88-4467-487f-bcfc-ea5a473afafd)

<br/>

## 리뷰어가 중점적으로 확인해야 하는 부분
- `Spending` 객체를 수정하는 과정이 마음에 들지 않습니다... 리팩토링을 하고싶은데 좋은 방법이 있으면 공유 부탁드립니다.
    - 현재 도메인에 `udpatedSpending` 정보들 한번에 전달하기 위해 `request.toEntity()`를 사용하고 있습니다. 이때 단순히 데이터를 domain 모듈로 전달하기 위해서 `Spending` 객체를 만들어야 합니다.
    - `Spending` 객체를 만들기 위해 필요도 없는 `User` 객체도 DB에서 조회 해야합니다.

- 그에 따른 `Spending.java` 의 `update` 메소드 수정 방식이 적절한가? 에 대한 의견도 궁금합니다!

- 수정 후 `Spending` 객체를 반환할 필요가 있을까요?
<br/>
## 발견한 이슈
X

2024-05-16 12:44 UTC, psychology50 requested changes
> Spending.java 의 update 메소드 수정 방식이 적절한가? 에 대한 의견도 궁금합니다!
- Spending 엔티티 자체의 update 메서드는 딱히 문제가 없다고 생각합니다.

<br/>

> 수정 후 Spending 객체를 반환할 필요가 있을까요?
- 안 해도 동작은 하겠지만, 사용자가 수정 후 요청한 값과 실제 서버에 저장된 값이 다를 수 있기 때문에 후자의 데이터를 사용자에게 보여주는 게 더 낫다고 생각합니다.  
- 그리고 지출 조회 메인 UI에서 불러오는 데이터가 너무 많아서, 추가/수정이 발생했을 땐 단발성 데이터로 관리하는 게 안전할 거 같아요. 물론 프론트에서 그렇게 섬세하게 데이터를 다뤄주실 진 모르겠지만..

2024-05-16 12:44 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/SpendingApi.java
> +            @ApiResponse(responseCode = "403", description = "지출 카테고리에 대한 권한이 없습니다.", content = @Content(examples = {
P4: 이 403에러는 사실 Client가 뻘짓만 안 하면 발생하지 않을 에러기도 하고, 기본 에러 응답 리스트에 포함된 거라 제외해도 괜찮습니다. 있어도 괜찮긴 한데, 주석 너무 길어서 전 보통 안 쓰는 편 ㅎ

2024-05-16 12:44 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingUseCase.java
> +    public SpendingSearchRes.Individual getSpedingDetail(Long spendingId) {
P5: 이렇게 사소해보이지만 현재 PR과 관련 없는 수정이 발생했을 때 가장 큰 문제점은 리뷰어는 그 사실을 모른다는 겁니다. 어떤 의도를 가지고 이러한 작업을 했는지 확인하느라 집중이 풀려버려요.  
저도 그 점을 의식하기 때문에 되도록 수정을 안 하려고 하지만, 너무 사소한 경우에는 PR 서두에 밝히고 시작합니다.

2024-05-16 12:44 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingUseCase.java
> +        Spending updatedSpending = spendingService.updateSpending(spendingId, request.toEntity(user));
P3: User를 조회해야 하는 이유가 *toEntity*(*User user*) 메서드에서 user를 매핑시켜주기 위해 그런 것 같은데, 그냥 *toEntity*() 하나 더 정의해서 fk가 null인 Entity를 만들면 되지 않을까요.  
그보다 이거 위험한 게, 만약 `User`가 `Spending`의 역방향 관계를 가지도록 수정하게 되면 영속화된 User 때문에 얘도 `insert`될 수도 있어요.  

<br/>

그냥 수정을 위한 `Spending` Entity 생성할 때, user를 null로 넣으시면 될 거 같은디..  
근데 toEntity에 null 넣으면 안 이쁘니까, 별도로 메서드 만들어도 괜찮을 듯..? 위험하려나 ㅎㅎ;

2024-05-16 12:44 UTC, psychology50 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingService.java
> +        Spending spending = spendingRepository.findById(spendingId)
P2: update를 위한 메서드 내부에서 spending을 조회하는 메서드가 숨어있는 건 부적절하다고 생각합니다.  
그보다 더 근본적인 질문이 해당 작업을 하기 위해 Domain Service가 관여해야 할 이유가 있을까요?  
Spending이 영속화된 상태에서 수정이 발생하면 `Dirty Checking`에 의해 수정 쿼리가 날아갈텐데 말이죠.

2024-05-16 13:29 UTC, asn6878 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/SpendingApi.java
> +            @ApiResponse(responseCode = "403", description = "지출 카테고리에 대한 권한이 없습니다.", content = @Content(examples = {
이 부분이 지출 생성에는 존재했어서, 저도 넣을까 말까 고민했는데 주석이 너무 지저분해서 제거 하는게 나을 것 같네요.
반영하겠습니다~~

2024-05-16 17:31 UTC, asn6878 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingService.java
> +        Spending spending = spendingRepository.findById(spendingId)
`SpendingService.readSpending()` 으로 수정하고자 하는 `Spending` 객체를 영속화 하고, 바로 수정해주자니 `readSpending` 메소드 에 `@Transactional(readOnly = true)`가 있어서, 이걸 마음대로 떼버리면 기존에 해당 메소드를 사용하는 다른 동작들이 보호받지 못할 것이라고 생각했어요.

#### 대안

> `readOnly = true` 가 아닌 `readSpending` 메서드를 추가로 작성해서 사용한다. -> `UseCase` 단에서 `Spending` 객체를 바로 수정할 수 있다.

정도가 생각나는데, 어떻게 생각하시나요??

2024-05-16 17:34 UTC, asn6878 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingUseCase.java
> +        Spending updatedSpending = spendingService.updateSpending(spendingId, request.toEntity(user));
말씀주신대로 일단은 `User`가 `Spending`을 역방향으로 참조할 일이 당장은 없어 보이긴 하니, 일단은 `toEntity` 오버로딩해서 사용하겠습니다.

2024-05-17 02:44 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingUseCase.java
> +        Spending updatedSpending = spendingService.updateSpending(spendingId, request.toEntity(user));
참조할 일이 없어 보이긴 하지만 문제는 이런 거죠.  

하다보니 역참조가 필요할 거 같아서 내부적으로 변경했을 때, 성윤님의 코드 상에서 어떠한 컴파일 에러도 발생하지 않아요.  
문제는 이걸 테스트 케이스로 잡아내기라도 할 것이냐는 건데, 위험하지 않을까요?

2024-05-17 02:49 UTC, psychology50 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingService.java
> +        Spending spending = spendingRepository.findById(spendingId)
`readOnly` 옵션은 DB Lock 레벨을 제어하는 거라 다른 동작에 문제가 발생하진 않습니다.  
다만, *readSpending*()에 `readOnly` 레벨의 트랜잭션이 걸려있다고 해서, Usecase의 수정이 막히는 부분이 이해가 안 됩니다.  

상위 수준에서 `@Transaction`의 기본 트랜잭션 레벨을 사용하면 그럴 일이 없을 텐데요..??

2024-05-17 05:11 UTC, asn6878 commented on pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingService.java
> +        Spending spending = spendingRepository.findById(spendingId)
아하, 저는 단순히 `readSpending()`에 readOnly가 걸려있어서, 해당 메소드를 통해 가져온(영속화 한) 엔티티들은 변경 요청 발생 시 반드시 오류가 난다고 생각하고있었어요.

상위 수준에서 읽기, 쓰기 트랜잭션 레벨을 사용하면, 하위 트랜잭션 레벨은 뭘 쓰던 관계없이 상위 수준에 지배되는게 맞죠. 실제로도 수정동작 문제없이 잘 되어서, 이 부분은 일단 현 상태에서 굳이 변경할 필요가 없을것 같네요.
배워갑니다 👍

2024-05-28 02:53 UTC, psychology50 approved these changes
테스트 케이스까지 작성하느라 수고 많으셨습니다~  
커멘트 몇 개 남겨뒀는데 수정해볼 생각있으면 해보셔도 좋을 거 같아요.

2024-05-28 02:53 UTC, psychology50 commented on pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/SpendingControllerIntegrationTest.java
> +        @DisplayName("권한이 없는 사용자가 해당 지출 내역 조회시 403 Forbidden을 반환한다.")
P5: 수정할 필요는 아니지만, "권한이 없다"라는 말엔 다양한 의미가 있습니다. 저는 처음에 access token이 유효하지 않은 사용자를 의미하는 줄 알았어요.  
테스트는 언제나 명료해야 합니다. 그래서 보다 구체적으로 테스트하고자 하는 상황을 설명하는 것이 좋다고 생각합니다.

2024-05-28 02:53 UTC, psychology50 commented on pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/SpendingControllerIntegrationTest.java
> +            Assertions.assertEquals("수정된 메모", updatedSpending.getMemo());
P5: expectedValue에 "수정된 메모"를 직접 입력해도 되지만 given 절의 request가 수정되면 매번 함께 수정해주어야 합니다. 여기서 예상값은 `request.accountName()`으로 표현할 수도 있을 거 같아요.

2024-05-28 02:53 UTC, psychology50 commented on pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/service/SpendingUpdateServiceTest.java
> +        request = new SpendingReq(10000, -1L, SpendingCategory.FOOD, LocalDate.now(), "소비처", "메모");
P5: Request 정보도 매번 만들기 힘들다면, 이럴 때 `SpendigFixture`를 활용할 수 있습니다.  
제가 사용했던 것처럼 `UserFixture`를 만들고 반환값을 SpendingReq로 만들면 돼요.

2024-05-28 02:53 UTC, psychology50 commented on pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/fixture/SpendingFixture.java
> +    public static Spending toSpending(User user) {
P5: 이거 지출 내역 삭제 테스트에서 설명했었던 거 같긴 한데, 제가 UserFixture에서 사용한 것처럼 여러가지 케이스의 Spending 상수를 정의하고 사용할 수도 있어요.

2024-05-28 03:02 UTC, psychology50 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingUseCase.java
> +        Spending updatedSpending = spendingService.updateSpending(spendingId, request.toEntity(user));
제가 승인해버리고 나서 이걸 확인했는데 문제가 있을 수 있는 부분이 있어 언급합니다.  
현재 시점에선 넘어가도 괜찮을 거 같긴 한데, 잘 모르겠네요.  

제가 Spending이라는 객체를 업데이트 할 때는 언제나 유효성 검사를 수행해주었습니다.  
아래와 같은 방법으로요.

![image](https://github.com/CollaBu/pennyway-was/assets/96044622/66f20cfe-277a-48b8-b489-881027d683d9)

하지만 성윤님의 *update*()는 아무런 제약을 받지 않아요.

![image](https://github.com/CollaBu/pennyway-was/assets/96044622/0129efac-a163-4ab3-a2a5-7baab722ac60)

다만, 업데이트를 위해서 Spending 인스턴스를 넘겨야 하므로 반드시 생성자의 유효성 검사를 거치게 될 거라는 점을 감안하면 큰 문제가 없을 거라 생각하긴 합니다.

2024-05-29 02:08 UTC, asn6878 commented on pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingUseCase.java
> +        Spending updatedSpending = spendingService.updateSpending(spendingId, request.toEntity(user));
말씀 해 주신 것처럼 `update` 메서드 를 호출하기 위해 request를 `toEntity`메소드로 변환하는 과정에 카테고리 유효성 검사가 포함되어있습니다! 확인되시면 resolve 해주시면 감사하겠습니다 😄

2024-05-29 11:27 UTC, psychology50 commented
테스트 케이스 수정된 거 모두 확인했습니다.  
개선의 여지가 조금 더 있긴 하지만 충분하다고 생각해요.

2024-05-29 14:59 UTC, merged